# python 

def scattertable(key):
  # Estelle dictionary fuer die plotfarbe
    design_tab = {'colors': { "ssp245": "tab:cyan",
                              "rcp45" : "tab:blue",
                              "ssp126": "tab:olive", 
                              "rcp26" : "tab:green",
                              "ssp119": "tab:gray",
                              "ssp370": "tab:red", 
                              "ssp434": "darkgreen", 
                              "ssp460": "tab:orange",
                              "ssp534-over": "tab:brown", 
                              "ssp585": "tab:pink",
                              "rcp85" : "tab:purple", 
                              "rcp26-CMIP5-CORDEX" : "xkcd:black",
                              "rcp45-CMIP5-CORDEX" : "xkcd:black",
                              "rcp85-CMIP5-CORDEX" : "xkcd:black",
                              "CMIP5-CORDEX" : "xkcd:black",
                              "ssp370_MIROC6": "tab:orange", # fuer Kevin special
                              "ssp370_EC-EARTH3-Veg": "tab:brown", # fuer Kevin
                              "ssp370_MPI-ESM1-2-HR": "tab:pink" # fuer Kevin
                              },
                 # plotting CORDEX and CMIP5 together the color is (forcing)GCM
                  'colors-cordex': { "EC-EARTH_r12i1p1":"tab:cyan",
                               "EC-EARTH_r1i1p1": "xkcd:indigo", 
                               "EC-EARTH_r3i1p1": "tab:blue", 
                               "MPI-ESM-LR_r1i1p1": "xkcd:magenta",
                               "MPI-ESM-LR_r2i1p1": "tab:purple",
                               "MPI-ESM-LR_r3i1p1": "tab:pink",
                               "CNRM-CM5_r1i1p1": "darkgreen", 
                               "HadGEM2-ES_r1i1p1": "tab:red",
                               "MIROC5_r1i1p1": "tab:green",     
                               "NorESM1-M_r1i1p1": "peru", 
                               "GFDL-ESM2G_r1i1p1": "tab:olive", 
                               "CanESM2_r1i1p1": "tab:orange",
                               "IPSL-CM5A-LR_r1i1p1": "gold", 
                               "IPSL-CM5A-MR_r1i1p1": "tab:brown",
                               "CMIP5": "tab:gray",
                              },
                  'marker-rcm': { "CMIP5": "o", #                    
                                  "UHOH-WRF361H": "^",  
                                  "IPSL-WRF381P": "v",
                                  "CLMcom-ETH-COSMO-crCLIM-v1-1": "*",
                                  "CLMcom-CCLM4-8-17": "P",   
                                  "GERICS-REMO2015": "p",
                                  "MPI-CSC-REMO2009": "p",
                                  "ICTP-RegCM4-6": "s", 
                                  "MOHC-HadREM3-GA7-05": "d",
                                  "KNMI-RACMO22E": "D", 
                                  "SMHI-RCA4": "<", 
                                  "DMI-HIRHAM5": ">", 
                                  "CNRM-ALADIN63": "X", #x
                              },
                  'marker': { "CMIP6": "^",   #"X",                       
                              "CMIP5": "o",           
                              "CMIP5-CORDEX": "*",
                              "MEAN" :"X",
                              },
                  'cordex-gcm': { "CNRM-CM5_r1i1p1_historical": "CMIP5-CORDEX",
                                  "GFDL-ESM2G_r1i1p1_historical": "CMIP5-CORDEX",
                                  "HadGEM2-ES_r1i1p1_historical": "CMIP5-CORDEX",
                                  "MPI-ESM-LR_r1i1p1_historical": "CMIP5-CORDEX",
                                  "MPI-ESM-LR_r2i1p1_historical": "CMIP5-CORDEX",
                                  "MPI-ESM-LR_r3i1p1_historical": "CMIP5-CORDEX",
                                  "NorESM1-M_r1i1p1_historical": "CMIP5-CORDEX",
                                  "EC-EARTH_r1i1p1_historical": "CMIP5-CORDEX",
                                  "EC-EARTH_r3i1p1_historical": "CMIP5-CORDEX",
                                  "EC-EARTH_r12i1p1_historical": "CMIP5-CORDEX",
                                  "IPSL-CM5A-LR_r1i1p1_historical": "CMIP5-CORDEX",
                                  "IPSL-CM5A-MR_r1i1p1_historical" : "CMIP5-CORDEX" ,
                                  "CanESM2_r1i1p1_historical": "CMIP5-CORDEX" ,
                                  "MIROC5_r1i1p1_historical": "CMIP5-CORDEX" ,
                                  "CNRM-CM5_r1i1p1_rcp26": "CMIP5-CORDEX",
                                  "CNRM-CM5_r1i1p1_rcp45": "CMIP5-CORDEX",
                                  "CNRM-CM5_r1i1p1_rcp85": "CMIP5-CORDEX",
                                  "GFDL-ESM2G_r1i1p1_rcp26": "CMIP5-CORDEX",
                                  "HadGEM2-ES_r1i1p1_rcp26": "CMIP5-CORDEX",
                                  "HadGEM2-ES_r1i1p1_rcp45": "CMIP5-CORDEX",
                                  "HadGEM2-ES_r1i1p1_rcp85": "CMIP5-CORDEX",
                                  "MPI-ESM-LR_r1i1p1_rcp26": "CMIP5-CORDEX",
                                  "MPI-ESM-LR_r1i1p1_rcp45": "CMIP5-CORDEX",
                                  "MPI-ESM-LR_r1i1p1_rcp85": "CMIP5-CORDEX",
                                  "MPI-ESM-LR_r2i1p1_rcp26": "CMIP5-CORDEX",
                                  "MPI-ESM-LR_r2i1p1_rcp45": "CMIP5-CORDEX",
                                  "MPI-ESM-LR_r2i1p1_rcp85": "CMIP5-CORDEX",
                                  "MPI-ESM-LR_r3i1p1_rcp85": "CMIP5-CORDEX",
                                  "NorESM1-M_r1i1p1_rcp26": "CMIP5-CORDEX",
                                  "NorESM1-M_r1i1p1_rcp45": "CMIP5-CORDEX",
                                  "NorESM1-M_r1i1p1_rcp85": "CMIP5-CORDEX",
                                  "EC-EARTH_r1i1p1_rcp85": "CMIP5-CORDEX",
                                  "EC-EARTH_r3i1p1_rcp26": "CMIP5-CORDEX",
                                  "EC-EARTH_r3i1p1_rcp45": "CMIP5-CORDEX",
                                  "EC-EARTH_r3i1p1_rcp85": "CMIP5-CORDEX",
                                  "EC-EARTH_r12i1p1_rcp26": "CMIP5-CORDEX",
                                  "EC-EARTH_r12i1p1_rcp45": "CMIP5-CORDEX",
                                  "EC-EARTH_r12i1p1_rcp85": "CMIP5-CORDEX",
                                  "IPSL-CM5A-LR_r1i1p1_rcp26": "CMIP5-CORDEX",
                                  "IPSL-CM5A-MR_r1i1p1_rcp45" : "CMIP5-CORDEX",
                                  "IPSL-CM5A-MR_r1i1p1_rcp85": "CMIP5-CORDEX" ,
                                  "CanESM2_r1i1p1_rcp85": "CMIP5-CORDEX" ,
                                  "MIROC5_r1i1p1_rcp26": "CMIP5-CORDEX" ,
                                  "MIROC5_r1i1p1_rcp85": "CMIP5-CORDEX" ,
                                  },
                  'cmip6-gcm-lbc': {"ACCESS-CM2_gn_r1i1p1f1_historical": "CMIP6-LBC",
                                    "CESM2_gn_r10i1p1f1_historical": "CMIP6-LBC",
                                    "CMCC-CM2-SR5_gn_r1i1p1f1_historical": "CMIP6-LBC",
                                    "CMCC-ESM2_gn_r1i1p1f1_historical": "CMIP6-LBC",
                                    "CNRM-CM6-1_gr_r1i1p1f2_historical": "CMIP6-LBC",
                                    "CNRM-ESM2-1_gr_r1i1p1f2_historical": "CMIP6-LBC",
                                    "CanESM5_gn_r1i1p1f1_historical": "CMIP6-LBC",
                                    "EC-Earth3-Veg_gr_r1i1p1f1_historical": "CMIP6-LBC", 
                                    "HadGEM3-GC31-LL_gn_r1i1p1f3_historical": "CMIP6-LBC", 
                                    "HadGEM3-GC31-MM_gn_r1i1p1f3_historical": "CMIP6-LBC",
                                    "IPSL-CM6A-LR_gr_r1i1p1f1_historical": "CMIP6-LBC", 
                                    "MIROC6_gn_r1i1p1f1_historical": "CMIP6-LBC",   
                                    "MIROC-ES2L_gn_r1i1p1f2_historical": "CMIP6-LBC",  
                                    "MPI-ESM1-2-HR_gn_r1i1p1f1_historical": "CMIP6-LBC", 
                                    "MPI-ESM1-2-LR_gn_r1i1p1f1_historical": "CMIP6-LBC", 
                                    "NorESM2-LM_gn_r1i1p1f1_historical": "CMIP6-LBC",
                                    "NorESM2-MM_gn_r1i1p1f1_historical": "CMIP6-LBC",
                                    "MRI-ESM2-0_gn_r1i1p1f1_historical": "CMIP6-LBC", 
                                    "TaiESM1_gn_r1i1p1f1_historical": "CMIP6-LBC", 
                                    "UKESM1-0-LL_gn_r1i1p1f2_historical": "CMIP6-LBC",
                                    "ACCESS-CM2_gn_r1i1p1f1_ssp126": "CMIP6-LBC",
                                    "ACCESS-CM2_gn_r1i1p1f1_ssp245": "CMIP6-LBC",
                                    "ACCESS-CM2_gn_r1i1p1f1_ssp585": "CMIP6-LBC",
                                    "ACCESS-CM2_gn_r1i1p1f1_ssp370": "CMIP6-LBC",
                                    "CESM2_gn_r10i1p1f1_ssp126": "CMIP6-LBC",
                                    "CESM2_gn_r10i1p1f1_ssp245": "CMIP6-LBC",
                                    "CESM2_gn_r10i1p1f1_ssp585": "CMIP6-LBC",
                                    "CESM2_gn_r11i1p1f1_ssp370": "CMIP6-LBC",
                                    "CMCC-CM2-SR5_gn_r1i1p1f1_ssp126": "CMIP6-LBC",
                                    "CMCC-CM2-SR5_gn_r1i1p1f1_ssp245": "CMIP6-LBC",
                                    "CMCC-CM2-SR5_gn_r1i1p1f1_ssp370": "CMIP6-LBC",
                                    "CMCC-CM2-SR5_gn_r1i1p1f1_ssp585": "CMIP6-LBC",
                                    "CMCC-ESM2_gn_r1i1p1f1_ssp126": "CMIP6-LBC",
                                    "CMCC-ESM2_gn_r1i1p1f1_ssp245": "CMIP6-LBC",
                                    "CMCC-ESM2_gn_r1i1p1f1_ssp585": "CMIP6-LBC",
                                    "CNRM-CM6-1_gr_r1i1p1f2_ssp245": "CMIP6-LBC",
                                    "CNRM-CM6-1_gr_r1i1p1f2_ssp585": "CMIP6-LBC",
                                    "CNRM-ESM2-1_gr_r1i1p1f2_ssp126": "CMIP6-LBC",
                                    "CNRM-ESM2-1_gr_r1i1p1f2_ssp245": "CMIP6-LBC",
                                    "CNRM-ESM2-1_gr_r1i1p1f2_ssp585": "CMIP6-LBC",
                                    "CNRM-ESM2-1_gr_r1i1p1f2_ssp370": "CMIP6-LBC",
                                    "CanESM5_gn_r1i1p1f1_ssp126": "CMIP6-LBC",
                                    "CanESM5_gn_r1i1p1f1_ssp245": "CMIP6-LBC",
                                    "CanESM5_gn_r1i1p1f1_ssp585": "CMIP6-LBC",
                                    "CanESM5_gn_r1i1p1f1_ssp370": "CMIP6-LBC",
                                    "EC-Earth3-Veg_gr_r1i1p1f1_ssp370": "CMIP6-LBC",
                                    "EC-Earth3-Veg_gr_r1i1p1f1_ssp585": "CMIP6-LBC",
                                    "EC-Earth3-Veg_gr_r1i1p1f1_ssp126": "CMIP6-LBC",
                                    "EC-Earth3-Veg_gr_r12i1p1f1_ssp245": "CMIP6-LBC",
                                    "HadGEM3-GC31-LL_gn_r1i1p1f3_ssp245": "CMIP6-LBC",
                                    "HadGEM3-GC31-LL_gn_r1i1p1f3_ssp126": "CMIP6-LBC",
                                    "HadGEM3-GC31-LL_gn_r1i1p1f3_ssp585": "CMIP6-LBC",
                                    "HadGEM3-GC31-MM_gn_r1i1p1f3_ssp585": "CMIP6-LBC",
                                    "HadGEM3-GC31-MM_gn_r1i1p1f3_ssp126": "CMIP6-LBC",
                                    "IPSL-CM6A-LR_gr_r1i1p1f1_ssp126": "CMIP6-LBC", 
                                    "IPSL-CM6A-LR_gr_r1i1p1f1_ssp245": "CMIP6-LBC",
                                    "IPSL-CM6A-LR_gr_r1i1p1f1_ssp585": "CMIP6-LBC",
                                    "IPSL-CM6A-LR_gr_r1i1p1f1_ssp370": "CMIP6-LBC",
                                    "MIROC6_gn_r1i1p1f1_ssp126": "CMIP6-LBC",
                                    "MIROC6_gn_r3i1p1f1_ssp245": "CMIP6-LBC",
                                    "MIROC6_gn_r1i1p1f1_ssp585": "CMIP6-LBC",
                                    "MIROC6_gn_r1i1p1f1_ssp370": "CMIP6-LBC",
                                    "MIROC-ES2L_gn_r1i1p1f2_ssp126": "CMIP6-LBC", 
                                    "MIROC-ES2L_gn_r1i1p1f2_ssp245": "CMIP6-LBC",
                                    "MIROC-ES2L_gn_r1i1p1f2_ssp585": "CMIP6-LBC",
                                    "MIROC-ES2L_gn_r1i1p1f2_ssp370": "CMIP6-LBC",
                                    "MPI-ESM1-2-HR_gn_r1i1p1f1_ssp126": "CMIP6-LBC",  
                                    "MPI-ESM1-2-HR_gn_r1i1p1f1_ssp245": "CMIP6-LBC",
                                    "MPI-ESM1-2-HR_gn_r1i1p1f1_ssp585": "CMIP6-LBC", 
                                    "MPI-ESM1-2-HR_gn_r1i1p1f1_ssp370": "CMIP6-LBC",
                                    "MPI-ESM1-2-LR_gn_r1i1p1f1_ssp126": "CMIP6-LBC", 
                                    "MPI-ESM1-2-LR_gn_r1i1p1f1_ssp245": "CMIP6-LBC",
                                    "MPI-ESM1-2-LR_gn_r1i1p1f1_ssp585": "CMIP6-LBC",
                                    "MPI-ESM1-2-LR_gn_r1i1p1f1_ssp370": "CMIP6-LBC",
                                    "MRI-ESM2-0_gn_r1i1p1f1_ssp126": "CMIP6-LBC",
                                    "MRI-ESM2-0_gn_r1i1p1f1_ssp585": "CMIP6-LBC",
                                    "NorESM2-LM_gn_r1i1p1f1_ssp126": "CMIP6-LBC",
                                    "NorESM2-LM_gn_r1i1p1f1_ssp245": "CMIP6-LBC",
                                    "NorESM2-LM_gn_r1i1p1f1_ssp585": "CMIP6-LBC",
                                    "NorESM2-LM_gn_r1i1p1f1_ssp370": "CMIP6-LBC", 
                                    "NorESM2-MM_gn_r1i1p1f1_ssp126": "CMIP6-LBC",                      
                                    "NorESM2-MM_gn_r1i1p1f1_ssp370": "CMIP6-LBC",
                                    "NorESM2-MM_gn_r1i1p1f1_ssp585": "CMIP6-LBC",
                                    "TaiESM1_gn_r1i1p1f1_ssp126": "CMIP6-LBC",
                                    "TaiESM1_gn_r1i1p1f1_ssp245": "CMIP6-LBC",
                                    "TaiESM1_gn_r1i1p1f1_ssp585": "CMIP6-LBC",
                                    "TaiESM1_gn_r1i1p1f1_ssp370": "CMIP6-LBC",
                                    "UKESM1-0-LL_gn_r1i1p1f2_ssp126": "CMIP6-LBC",
                                    "UKESM1-0-LL_gn_r1i1p1f2_ssp245": "CMIP6-LBC",
                                    "UKESM1-0-LL_gn_r1i1p1f2_ssp585": "CMIP6-LBC",
                                    "UKESM1-0-LL_gn_r1i1p1f2_ssp370": "CMIP6-LBC",
                                 },
                  'cmip6-gcm-lbc-kevin': { "MIROC6_gn_r1i1p1f1_ssp370": "ssp370_MIROC6", 
                                           "EC-Earth3-Veg_gr_r1i1p1f1_ssp370": "ssp370_EC-EARTH3-Veg",
                                           "MPI-ESM1-2-HR_gn_r1i1p1f1_ssp370": "ssp370_MPI-ESM1-2-HR", 
                                           }, 
                  'cmip6-gcm-lbc-kevin2': { "MIROC6_gn_r1i1p1f1_ssp370": "ssp370_LBC", 
                                           "EC-Earth3-Veg_gr_r1i1p1f1_ssp370": "ssp370_LBC",
                                           "MPI-ESM1-2-HR_gn_r1i1p1f1_ssp370": "ssp370_LBC", 
                                           }, 
                  }

    return design_tab[key]
